//
//  NewsDetailsModels.swift
//  TopNews
//
//  Created by Sujata Chakraborty on 11/10/2019.
//  Copyright (c) 2019 Sujata Chakraborty. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum NewsDetails
{
  // MARK: Use cases
  
  enum FetchNewsDetails
  {
    struct Request
    {
        
    }
    struct Response
    {
        var news : News
    }
    struct ViewModel
    {
        struct DisplayNews
        {
            var title : String
            var url   : String
        }
        
        var newsDetails      : DisplayNews


    }
  }
}
